server:
  servlet:
    context-path: /EAD-Session-10
spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/employeePortal
    username: root
    password: deekshika
    driver-class-name : com.mysql.jdbc.Driver
    type: org.apache.tomcat.jdbc.pool.DataSource
  mail:
    host: smtp.gmail.com
    port: 587
    username: employeeportal123@gmail.com
    password: uqjlqhexkluvsvac
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
