use store_front;

DROP TABLE ProductCategory;
DROP TABLE OrderProduct;
DROP TABLE Image;
DROP TABLE Product;

CREATE TABLE Product(Id INT NOT NULL AUTO_INCREMENT,
Name VARCHAR(20) NOT NULL,
Price DOUBLE NOT NULL,
Description VARCHAR(200) NOT NULL,
Stock INT NOT NULL,
PRIMARY KEY(Id));

CREATE TABLE Image(Id INT NOT NULL AUTO_INCREMENT,
URL VARCHAR(100) NOT NULL,
Text VARCHAR(20),
FOREIGN KEY(Id) REFERENCES Product(Id),
PRIMARY KEY(Id));

CREATE TABLE OrderProduct(OrderId INT NOT NULL,
ProductId INT NOT NULL,
Status VARCHAR(20) NOT NULL,
DeliveryDate DATE NOT NULL,
ShipDate DATE NOT NULL,
Quantity INT NOT NULL,
PRIMARY KEY (OrderId, ProductId),
FOREIGN KEY(OrderId) REFERENCES Orders(Id) ON DELETE CASCADE,
FOREIGN KEY(ProductId) REFERENCES Product(Id) ON DELETE CASCADE);

CREATE TABLE ProductCategory(CategoryId INT NOT NULL,
ProductId INT NOT NULL,
PRIMARY KEY (CategoryId, ProductId),
FOREIGN KEY(CategoryId) REFERENCES Category(Id) ON DELETE CASCADE,
FOREIGN KEY(ProductId) REFERENCES Product(Id) ON DELETE CASCADE);
