use store_front;

CREATE TABLE User(Id INT NOT NULL AUTO_INCREMENT,
EmailId VARCHAR(100) NOT NULL UNIQUE,
FirstName VARCHAR(20) NOT NULL,
MiddleName VARCHAR(20),
LastName VARCHAR(20),
Password VARCHAR(100) NOT NULL,
Phone VARCHAR(15) NOT NULL,
PRIMARY KEY(Id));

CREATE TABLE Address(Id INT NOT NULL AUTO_INCREMENT,
Street VARCHAR(200) NOT NULL,
Landmark VARCHAR(50) NOT NULL,
City VARCHAR(15) NOT NULL,
State VARCHAR(15) NOT NULL,
PinCode INT(6) NOT NULL,
FOREIGN KEY(Id) REFERENCES User(Id),
PRIMARY KEY(Id));

CREATE TABLE Orders(Id INT NOT NULL AUTO_INCREMENT,
PlacedDate DATE NOT NULL,
Bill VARCHAR(20) NOT NULL,
FOREIGN KEY(Id) REFERENCES User(Id),
FOREIGN KEY(Id) REFERENCES Address(Id),
PRIMARY KEY(Id));

CREATE TABLE Product(Id INT NOT NULL AUTO_INCREMENT,
Name VARCHAR(20) NOT NULL,
Price DOUBLE NOT NULL,
Description VARCHAR(200) NOT NULL,
Stock INT NOT NULL,
PRIMARY KEY(Id));

CREATE TABLE Image(Id INT NOT NULL AUTO_INCREMENT,
URL VARCHAR(100) NOT NULL,
Text VARCHAR(20),
FOREIGN KEY(Id) REFERENCES Product(Id),
PRIMARY KEY(Id));

CREATE TABLE Category(Id INT NOT NULL AUTO_INCREMENT,
Name VARCHAR(20) NOT NULL,
ParentCategoryId INT,
PRIMARY KEY(Id));

CREATE TABLE Role(Id INT NOT NULL AUTO_INCREMENT,
Name VARCHAR(20) NOT NULL,
PRIMARY KEY(Id));

CREATE TABLE UserRole(UserId INT NOT NULL,
RoleId INT NOT NULL,
PRIMARY KEY (UserId, RoleId),
FOREIGN KEY(UserId) REFERENCES User(Id) ON DELETE CASCADE,
FOREIGN KEY(RoleId) REFERENCES Role(Id) ON DELETE CASCADE);

CREATE TABLE OrderProduct(OrderId INT NOT NULL,
ProductId INT NOT NULL,
Status VARCHAR(20) NOT NULL,
DeliveryDate DATE NOT NULL,
ShipDate DATE NOT NULL,
Quantity INT NOT NULL,
PRIMARY KEY (OrderId, ProductId),
FOREIGN KEY(OrderId) REFERENCES Orders(Id) ON DELETE CASCADE,
FOREIGN KEY(ProductId) REFERENCES Product(Id) ON DELETE CASCADE);

CREATE TABLE ProductCategory(CategoryId INT NOT NULL,
ProductId INT NOT NULL,
PRIMARY KEY (CategoryId, ProductId),
FOREIGN KEY(CategoryId) REFERENCES Category(Id) ON DELETE CASCADE,
FOREIGN KEY(ProductId) REFERENCES Product(Id) ON DELETE CASCADE);
